/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-COM4D.h
 #	source generated by 4D Plugin Wizard
 #	Project : COM4D
 #	author : miyako
 #	2020/03/19
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_COM4D_H
#define PLUGIN_COM4D_H

#include "4DPluginAPI.h"

#if VERSIONWIN

#include "4DPlugin-JSON.h"

#include "ichigocomhelper.h"
#include "json/json.h"

#include <olectl.h>
#include <iostream>
#include <new>
#include <exception>
#include <vector>
#include <mutex>
#include <iomanip>

typedef enum {
	com_setup_register = 0,
	com_setup_unregister = 1,
	com_setup_get_status = 2
} com_setup_t;

#endif

void COM_Setup(PA_PluginParameters params);
void COM_Write(PA_PluginParameters params);
void COM_Read(PA_PluginParameters params);

#endif /* PLUGIN_COM4D_H */
